// --- Day 2: Rock Paper Scissors ---
// The Elves begin to set up camp on the beach. To decide whose tent gets to be closest to the snack storage, a giant Rock Paper Scissors tournament is already in progress.

// Rock Paper Scissors is a game between two players. Each game contains many rounds; in each round, the players each simultaneously choose one of Rock, Paper, or Scissors using a hand shape. Then, a winner for that round is selected: Rock defeats Scissors, Scissors defeats Paper, and Paper defeats Rock. If both players choose the same shape, the round instead ends in a draw.

// Appreciative of your help yesterday, one Elf gives you an encrypted strategy guide (your puzzle input) that they say will be sure to help you win. "The first column is what your opponent is going to play: A for Rock, B for Paper, and C for Scissors. The second column--" Suddenly, the Elf is called away to help with someone's tent.

// The second column, you reason, must be what you should play in response: X for Rock, Y for Paper, and Z for Scissors. Winning every time would be suspicious, so the responses must have been carefully chosen.

// The winner of the whole tournament is the player with the highest score. Your total score is the sum of your scores for each round. The score for a single round is the score for the shape you selected (1 for Rock, 2 for Paper, and 3 for Scissors) plus the score for the outcome of the round (0 if you lost, 3 if the round was a draw, and 6 if you won).

// Since you can't be sure if the Elf is trying to help you or trick you, you should calculate the score you would get if you were to follow the strategy guide.

// For example, suppose you were given the following strategy guide:

// A Y
// B X
// C Z
// This strategy guide predicts and recommends the following:

// In the first round, your opponent will choose Rock (A), and you should choose Paper (Y). This ends in a win for you with a score of 8 (2 because you chose Paper + 6 because you won).
// In the second round, your opponent will choose Paper (B), and you should choose Rock (X). This ends in a loss for you with a score of 1 (1 + 0).
// The third round is a draw with both players choosing Scissors, giving you a score of 3 + 3 = 6.
// In this example, if you were to follow the strategy guide, you would get a total score of 15 (8 + 1 + 6).

// What would your total score be if everything goes exactly according to your strategy guide?


let input = "BZCZCZAYBZCYCZCYCXAZBZCZAYCZBXCYCZCXCXCYCYCXAYCYCYCXCZCXAXCZCYCZCZCZAZCZBZAYAXAYCZAYCZAZCYCYCYAXCXCXCYAXAYCXAXCZAYCZCYAYCZAXAYAXCXCZAXBZCZCYCXCXCZCXCZAXCYAYCYCZCXBXBZCZCXAXBZAYAYBZAYCYBZBXCXCXCXAXAZAYAYCYCZCZCZAYCXAYAXCXCXAXAYAXAXAYCYAYAYAXCXBZAXCYCXCZCZCZCZCYCXCXAXAYAXCZCXCYCYCZCZBZCZCYCXCYAXAYCXBZBYCZCYCXAYCYBZAZCXCZCYCXCZAXAYCYCYAYAXAXCXCXCZAYAYCYCZAXAYCXCXCYCXCZCXCZCZCZCZAYBZCYCZAZCXCXAXAZCZCXCZAXBZBZAXCXCXBZBZBZCZCXAYCZAXCYCZCZCXCXCZCYCYCXCXAXCYAXCYCXBXBZCXCXBXCZCYAXCZCZCZCYCXAYAZCZBZCZCXAYCXCXAXCXCZAXCZCYCYCYCZAXCYCXCZAXCZCXCXCXAYCZAYCZCYCZAYCXCXCXCYCZCXCYCXAXCXCYCXCZCXBZCXBZBXCXCXCXBXAYAYAXBZCXAZCYCXCXCYAYAZCXAYCZCXCXCYCYAZAXCZCXCZBYAYCZAYCZAXCYCYCXAYCXCXBXCZCXCYCZCZCYCYCYCXBZCXCXCYCYCZBZCXCYBZCZAYCXCXAYCYCZCXAYAYCZCZCZAXCXCZCZCZAYAXCXCZCXCXCYAYCXCYCZCYAXCXCXCZAXBXCYAXCYCYCXCZBXCXCZAYCZCXAXCYAXCZAXCXCYCXCZCXCXCYAXCYAYCZCXCXAXAZCXCXCYBZAXAXCXBZCZAYCYCZCXAZCYAXCYCZCZCXCYCXCYCYCXAYBXCXAXAYCYCZCYCXAYCZCXCXAZCYCZAXCXCZAYAXBXCZBZCXAZCZAXAYCXAXBZCXCYCZCYCYCZCXBXCYBYCZAYAYCYCZAXCZCYBZCXAXCXCXCYCYCZAYCZAXAYCXCYCZCXAXBZCZAXCXCXCXBZCZCYBZAXCZCYAXCXBZCYCXCZCZCZCXCYBXAXBZCXCYCZCXCZCZCZCYAXCXCZAXCXCZBXCZBZAYAXCZCZCYCZCYCZAYBZAYCXAXAXAXBZCZBYCYAYAYCZAYCZCZAYCZCZCZAYCZCZCZCZAYCYAYCYCXCXCZCXCZCYAXCZBXCZAXCZCZCYCZCYCXCYBXCZCXCYAYCXCZCXCZCXAZCZCXCXBZCZCXAXCYAYCXCZCZAYAXBYCYCYCYCXAXCZCYCZCXCZCZCYBXCXCZCXCXCYAXBZAXCXCZBZAYCYBZCXAZAXCZCZCXAYBYCXCZBYAYAYCXAXCYCXCXCZAXAXAXBZCYCZCXAXBZCZCZCXCXCXCXCZCYCZCZCZAYCZCXCYCXBYAYCZCXCZAXAXCYCYCXCZCZCZCXCZCXCYCXCXCYCYBZCZCZBZCYCZCYBZCXCZCYCZAYCZBZCZCXCXAZCZCXAYAZAXCYCXCZCXCXCYCXCZCXCYCYCZCYCYCYAZAYCZCYCZCXAXCZCZAYCZCXCXCXCZCXCZCYAZCZCYCZCXCYCYCXCXCZAYCYBZAYCYCXCZCXCYCZAYAXCZBYCYAXCYCZBZCYCZCZBZCXAYCZCXBYBZCZBZCXAXAXBZCZCZCZCYAYCZBXCYAZCYCYAYCXCYBZCXCXCXBZCXBZAXCYCYAXCXAYCXAXCZAXCXCXAYCZCZCXCXBZAYCYCXAYCZAXCXBZCXCXBXBXBZCZCXAYBZBYCXCZAYCZCXCXBZCXAYAXAZCZCYBZCXAXCXAXCXCXCZAXBZCZCXCXAXCZCXCXCZCYCXAXCXCXCXAXCZCZCYBZCXAYCZCXCYBXAXCXBZCYBXAYBXCZCYCXCZAYAYCXAXCXCXAYAXBXCYAYCXCZAYCZBZCZAXCYCYCYAYAZAYCXCXAYCYAXCYAYCXCYBZCZCZBXCYBXAYAYAXAYCZCZCYBZAZCXCZAXCXCXCZCYCXAYCZBZAYAXCYBXCZAYCXCYCXAXCZCZCXCZAXCXCXAZBZAXCYCXAXCXCZCYAYCXAYAXCYAYCXAYCXBZCXCXCXCZCZCZBZCXBZCXAXAYAYAXCYAXCYAYBZCXCXCYCXCZAXAYCZAXCXCXBXCXAYCXCZBZAXBZCYCZCYCYCXCZCZCZAXCXAXAYAXCZCZAZCYBZAXCZCZCXCXAXAZCZCXCXCYCYCYAYAYCZAXCZCXAXCYCZCYAXAYAXCZBZCZAXCXCYCXCXCYCZCZCYCXAYCYCZBZCYCYAXCZBZCXBZBZCZCXCZAXCZCXAYAXAYCZCZCZCZCXBZCYCXBZCXAXAYCXAZAYAXCYCZCYCZBZCYCXAYBZCZCZCYCXCZAYCYAYCZBZCZAXCZCZCYCXCYAXCYCZCXAXBZCYCXCZCYAXCXAYAYCXCZCYBZBXCYCXCXCZCYCXCZCYAXBYAXAYCXAXAXAXCYBXBZCZCXCZAYCYCXBZAXCXAYCXCXCXBZCZCXBXCZCYCXCYCZCZCZAXCXCXCXBZCZAYCXBZBZAYAYBZCXCYAXCYCXCYCYCXBZCZCZCZCYAYCZCYAXCXCZCYAYCZCXBZCXCZCZCYAXAYCZAYCZCXCZCZAXAXCXBZBZCYAYCXCXCZCZAYCYCZAXCXCYAYCXCXAZCXCYCZCXBZCXAXCZCZAXCZCYCZCZAYCXCXCXCYCZCXCXCYBZAXCXAYBZAYAXAXBXCYAYCYCZAXCXAYAYCZCXCZCZCZCZAYAYAXCXAYCYAXCXCXCXBZCZBZAXCZCZCYCXCXCXCYAZBXBZCXBZAXAYCZBYCXCXAYCYCYCZCXAXBZCXAXAXCXAXCYBXCZCZCZCZCXCZCXCZCZAXCZCXBZAYCZBZCYCXCXCZCYCXCZCXBXCZAYCXBZAYAXCXCXBZCYCZCXCZCZCZBXCXCXCYBZAYCYCZAZAYCZCYCYAXBZBZCXAXCZBZCZCYCZCYAXCXCYCXBXCYAYCXCZAZCYAXCZCYBZCYCZAYCZCXAYCXCZCXBZCXAXCZCZCXCZCXCZCZAZAXBZBXCZCXBZCXCYCZCZAXAXCYBZAXCXCZAZAZCZCYCXCYCZAZAXAYCXCZAYCYAYAXCZCXCZCXBZAYCXAXCXBXCXAXCXAXCYAYCXAYCXCZCXBZAXCZAXCZCZCYCZCYCXAYCXAXCZCXAYCYCXCXCZCXCYCXCXCXCXAYAYAYCZCXBYBYAYCZCXAYCZCYCXCZAXCZCZCYAXAXCZCXCXCXCZCZAYCYAXBZCZCYCZAXCZCXCXAYCZCXCZCZAYCYCZAXCYCZAXCXAXCXCZCXCZCZCYCYAYCYAXCYCXCZCXAXCXAXAYAXCZAXCYCXAYCZCZCXBXCZCYAYBZCYCXBZCXAYAXAXAXCXAXCXCZCXAXCYAYCXCZCXCZCYCXAXCXCYAYAXBZCYBZCYCXAYCXCZCXCYAXCYCYCZCYCXCZCXCXCXCZCXAYAYCXCZBZCXCYCXCXCZCZCXCXAZAXCXBZCZCYCZCXCXCXCZCXAXAXCZCXAZCXAXAXCZAXAYCZAZAYCYCXAYAXCZCXAYBZCZAXCZCXAXAYCZCYCZCZBZCXCZCZCYCXCZCXCXBZBZAYBXBZCZAZCYCXCZCXCXAXCXAYBXCZCYCXCZCYCYCXBZCXBZCYCYCYCXCXAXAXAXCZAXCZCXCYCZCYAYCYAXAYCYCZCZAYCXCXAXCYCXCYAXCXCYCZCZBZAYCXBZCYAXCZCXCZBXCZCZCZCXCZCZCXCZCZBXAXCYCZAYCYCZCZCXAYAXCYCYAYCZCXCXCXAYCXBXCZCZCXCZCXAYAZCZCZBXCYAZAYCZCXCZCXAXAYCYAXCZCXCZBXCXCZBZCZCYCYAXCZCXCYCZCZAYCZCYCYAXBZCZAXCYCYCZAXCXCZCXCXCZCYCXCZBZCYAXAXCXCZAXCXBZCYCZCYCXCZBYCXCZAXCXAXCXCZBZCZCZAZCYCXAXCZAXAYCXCZCYAYCYCXAXCXCYCXCXCZCZCXCZAXAXCXCZBZAXCXCZCYCXBZCXCXCXBXCYAYCZAZAYAYCYBZCZCYCXCZCXBZBXAXAZAYCZCYCYCXBYCYCXCXBXCYCZBZCXCYAYCZCXCZAXCZAXAYCYAYCYCZAXCYCYCXBXCZCXCZCZCZCXCZCYCXCYCXCXCXCXAYCXAYCXCZAXAZCZCXCXCXCXBZCZCZCYCXCZCXBZBZCZCZCXCXCZBZCXAYCXCZCXCYCZCZCXCZAYAYCXCZCZCXCXBZCXCZCZCXCZAXCZBZCZAYCZCXCXBZAYCZAYCYAZCXAXCXAYCZCXCZCZCXCZAXBZCYCZCZCXCZBZCYCZCZAXBZAXBZCXCZAZAZCXAXAXBZAYAYAZCXCZCZCXCXCXAXCXCZCYCZCXCZCXAXAYCXAXCXBZBZBXCXAXBXCXAYCZCYCZCXAXAYCZBZCXBZCZBZAXAXCYBZCXBZAYCZAYCZCXAZCZCZBZAYBZCYCXAYAXAXCXCYBZCXCZCZAXAYCXCYBZCZCXAXCZCXCXBZCYAYAXCZBZCXCZAYCXBZCYBXCXCXCYAYAXCYCYCZCYCYCXBXCXAYCZCZAYCZCZCZCZCZCYAYCZAXCYCZCXCZCXAZCXAYBYBZAYAYCZCXBZBXBYCXCZBZAXCXCXCYAXCZCYAYAXAXBXAYCYCZCZCXCXAXCZAZAYAXCXAYBZCXCZCYCZCZCXCZAXAYCXCXCXCZCYCZBZCZBZAYAXCZCXCZCXAXCZCZCXCXCZAYAZAYCZCZCXCYCXCYAXCXAYBZBZCXCXCZCXAYAZAYCXCZAYCYCZBZAXCXCZCZAYAYAYAYCXBZAZBXAXBXCZCZCZBZAYCZCYCXCYAYCXCYCYAXCYCXCXCXCXAYAYCXCZCZAYCZAYCZCZCXCXCZCYCZAXAXCYBZAXBZBZCXCZCYAXCZCYCZCYAYBXCYCYCXCXCZCZCXAYCZBZCYCXCYCZCXAXAYCZBZCXCZCXCZCXAXCZAXBZCX";

//PART 1
let score = 0;
let rock = 1;
let paper = 2;
let scissors = 3;
let win = 6;
let draw = 3;
let loss = 0;

// for(var i = 0; i < input.length - 1; i+=2)
// {
//     //Opponent's Rock Wins (A v Z)
//     if(input[i] == 'A' && input[i + 1] == 'Z')
//     {
//         score += loss + scissors;
//     }
//     //Opponent's Paper Wins (B v X)
//     if(input[i] == 'B' && input[i + 1] == 'X')
//     {
//         score += loss + rock;
//     }
//     //Opponent's Scissors Wins (C v Y)
//     if(input[i] == 'C' && input[i + 1] == 'Y')
//     {
//         score += loss + paper;
//     }
//     //Our Rock Wins (C v X)
//     if(input[i] == 'C' && input[i + 1] == 'X')
//     {
//         score += win + rock;
//     }
//     //Our Paper Wins (A v Z)
//     if(input[i] == 'A' && input[i + 1] == 'Y')
//     {
//         score += win + paper;
//     }
//     //Our Scissors Wins (B v Z)
//     if(input[i] == 'B' && input[i + 1] == 'Z')
//     {
//         score += win + scissors;
//     }
//     //Rocks tie (A v X)
//     if(input[i] == 'A' && input[i + 1] == 'X')
//     {
//         score += draw + rock;
//     }
//     //Papers tie (B v Y)
//     if(input[i] == 'B' && input[i + 1] == 'Y')
//     {
//         score += draw + paper;
//     }
//     //Scissors tie (C v Z)
//     if(input[i] == 'C' && input[i + 1] == 'Z')
//     {
//         score += draw + scissors;
//     }
// }

//PART 2

for(var i = 0; i < input.length - 1; i+=2)
{
    //Opponent chooses Rock and we need to win
    if(input[i] == 'A' && input[i + 1] == 'Z')
    {
        score += win + paper;
    }
    //Opponent chooses Rock and we need to draw
    if(input[i] == 'A' && input[i + 1] == 'Y')
    {
        score += draw + rock;
    }
    //Opponent chooses Rock and we need to lose
    if(input[i] == 'A' && input[i + 1] == 'X')
    {
        score += lose + scissors;
    }

    //Opponent chooses Paper and we need to win
    if(input[i] == 'B' && input[i + 1] == 'Z')
    {
        score += win + scissors;
    }
    //Opponent chooses Paper and we need to draw
    if(input[i] == 'B' && input[i + 1] == 'Y')
    {
        score += draw + paper;
    }
    //Opponent chooses Paper and we need to lose
    if(input[i] == 'B' && input[i + 1] == 'X')
    {
        score += lose + rock;
    }

    //Opponent chooses Scissors and we need to win
    if(input[i] == 'C' && input[i + 1] == 'Z')
    {
        score += win + rock;
    }
    //Opponent chooses Scissors and we need to draw
    if(input[i] == 'C' && input[i + 1] == 'Y')
    {
        score += draw + scissors;
    }
    //Opponent chooses Scissors and we need to lose
    if(input[i] == 'C' && input[i + 1] == 'X')
    {
        score += lose + paper;
    }
}

console.log(score);